### ISSUE TITLE
Fatal error: Class 'watoki\reflect\ClassResolver' not found in 

### ISSUE THREAD

**Issue by danez** [rtens/mockster#15]
Fatal error: Class 'watoki\reflect\ClassResolver' not found in MethodTypeHint.php

Should watoki/reflect be a composer dependency?

**Comment by rtens** [comment]
mockster requires watoki/factory which requires watoki/reflect. But I guess watoki/reflect should still be a dependency of mockster since it's directly used.

How did this error occur? Does the following work for you?

**Comment by danez** [comment]
This works because it installs dev-master of factory, but we are using stable channels, so 0.2 is installed:

```json
{
    "name" : "test",
    "require" : {
        "php" : ">=5.5.0",
    },
    "require-dev" : {
        "rtens/mockster" : "~2.3.0",
    },
}
```

**Comment by rtens** [comment]
I created a releases for watoki/factory and watoki/reflect and tested installation with the composer.json you posted. This should solve your problem. Let me know if not so. And thanks for reporting it.
